# Generated by Django 2.1.7 on 2019-03-19 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finish', models.DateTimeField(blank=True, null=True)),
                ('primary', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
